import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { GlassPanel, PageHeader } from "@/components/domain/ui";
import { SubmitButton } from "@/components/domain/submit-button";
import { updateTask } from "@/app/actions";
import { getTenantContext } from "@/lib/tenant";

const status: Record<string, string> = { OPEN: "Abierta", IN_PROGRESS: "En curso", DONE: "Completada", CANCELLED: "Cancelada", PLANNED: "Planificada", CONFIRMED: "Confirmada" };

export default async function OperationsPage() {
  const { supabase } = await getTenantContext();
  const start = new Date(); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 14);
  const [{ data: tasks }, { data: activities }, { data: profiles }, { data: bookings }] = await Promise.all([
    supabase.from("operations_tasks").select("id,title,due_at,status,priority,assigned_to,bookings(reference)").neq("status", "CANCELLED").order("due_at"),
    supabase.from("activities").select("id,title,activity_type,starts_at,status,location,bookings(reference)").gte("starts_at", start.toISOString()).lte("starts_at", end.toISOString()).order("starts_at"),
    supabase.from("profiles").select("id,display_name").order("display_name"),
    supabase.from("bookings").select("id,reference,status,travel_start,travel_end,total_sale,currency,agencies(name),customers(first_name,last_name)").order("travel_start")
  ]);
  const grouped = new Map<string, typeof activities>();
  for (const activity of activities ?? []) { const day = activity.starts_at.slice(0, 10); grouped.set(day, [...(grouped.get(day) ?? []), activity]); }
  return <AppShell>
    <PageHeader eyebrow="Operaciones" title="Agenda y coordinación" description="Servicios, recogidas, vencimientos y tareas operativas vinculadas a cada reserva." actions={<Link href="/sales" className="rounded-lg bg-accent px-4 py-2.5 text-sm font-semibold text-white">Nueva reserva</Link>}/>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_1fr]">
      <GlassPanel className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Calendario de 14 días</h2><p className="mt-1 text-xs text-muted">Vista operativa por fecha de servicio.</p></div><span className="text-xs text-muted">{activities?.length ?? 0} actividades</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Array.from(grouped.entries()).map(([day, dayActivities]) => <div key={day} className="rounded-xl border bg-surface/50 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-accent">{new Intl.DateTimeFormat("es-ES", { weekday: "short", day: "2-digit", month: "short" }).format(new Date(`${day}T12:00:00`))}</p><div className="mt-3 space-y-2">{dayActivities?.map((activity) => { const booking = Array.isArray(activity.bookings) ? activity.bookings[0] : activity.bookings; return <div key={activity.id} className="rounded-lg bg-ink/[.035] p-2"><p className="text-sm font-medium">{activity.title}</p><p className="mt-1 text-[11px] text-muted">{new Date(activity.starts_at).toLocaleTimeString("es-ES", { hour: "2-digit", minute: "2-digit" })} · {booking?.reference ?? activity.activity_type}</p></div>; })}</div></div>)}</div>{!activities?.length ? <p className="mt-6 rounded-lg border border-dashed p-5 text-center text-sm text-muted">No hay actividades en los próximos 14 días. Al convertir una cotización, la agenda se genera automáticamente.</p> : null}</GlassPanel>
      <GlassPanel className="overflow-hidden"><div className="p-5"><h2 className="font-semibold">Cola de atención</h2><p className="mt-1 text-xs text-muted">Asigna responsables y avanza el estado desde aquí.</p></div><div className="divide-y">{tasks?.map((task) => { const booking = Array.isArray(task.bookings) ? task.bookings[0] : task.bookings; return <form action={updateTask} key={task.id} className="p-4"><input type="hidden" name="task_id" value={task.id}/><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{task.title}</p><p className="mt-1 text-xs text-muted">{booking?.reference ?? "Tarea general"} · vence {new Date(task.due_at).toLocaleString("es-ES", { dateStyle: "medium", timeStyle: "short" })}</p></div><span className={`rounded-md px-2 py-1 text-[11px] font-semibold ${task.priority === "HIGH" ? "bg-rose-500/10 text-rose-700" : "bg-ink/5 text-muted"}`}>{task.priority === "HIGH" ? "Alta" : "Normal"}</span></div><div className="mt-3 grid grid-cols-[1fr_1fr_auto] gap-2"><select name="assigned_to" defaultValue={task.assigned_to ?? ""} className="rounded-lg border bg-surface px-2 py-2 text-xs"><option value="">Sin asignar</option>{profiles?.map((profile) => <option key={profile.id} value={profile.id}>{profile.display_name}</option>)}</select><select name="status" defaultValue={task.status} className="rounded-lg border bg-surface px-2 py-2 text-xs"><option value="OPEN">Abierta</option><option value="IN_PROGRESS">En curso</option><option value="DONE">Completada</option><option value="CANCELLED">Cancelada</option></select><SubmitButton>Guardar</SubmitButton></div></form>; })}</div></GlassPanel>
    </div>
    <GlassPanel className="mt-5 overflow-hidden"><div className="p-5"><h2 className="font-semibold">Expedientes de reserva</h2><p className="mt-1 text-xs text-muted">Reservas recibidas desde cotizaciones aceptadas o carga directa.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-y bg-ink/[.025] text-xs text-muted"><tr><th className="px-5 py-3">Reserva</th><th>Titular</th><th>Viaje</th><th>Estado</th><th>Total</th></tr></thead><tbody>{bookings?.map((booking) => { const agency = Array.isArray(booking.agencies) ? booking.agencies[0] : booking.agencies; const customer = Array.isArray(booking.customers) ? booking.customers[0] : booking.customers; return <tr key={booking.id} className="border-b last:border-0"><td className="px-5 py-3 font-mono font-semibold text-accent">{booking.reference}</td><td>{agency?.name ?? (customer ? `${customer.first_name} ${customer.last_name}` : "—")}</td><td>{booking.travel_start} → {booking.travel_end}</td><td>{status[booking.status] ?? booking.status}</td><td>{booking.currency} {Number(booking.total_sale).toFixed(2)}</td></tr>; })}</tbody></table></div></GlassPanel>
  </AppShell>;
}
