"use client";
import Link from "next/link";
import { Bell, ChevronDown, CircleHelp, Command, LayoutDashboard, Landmark, Menu, Package, ReceiptText, Settings2, ShieldCheck, Users, X } from "lucide-react";
import { useState } from "react";
import { ThemeToggle } from "@/components/theme-toggle";
import { cn } from "@/lib/cn";

const groups = [{ label: "Espacio de trabajo", items: [["Panel", "/dashboard", LayoutDashboard], ["Ventas", "/sales", ReceiptText], ["Clientes y agencias", "/crm", Users]] }, { label: "Oferta", items: [["Productos", "/products", Package], ["Operaciones", "/operations", CircleHelp], ["Finanzas", "/finance", Landmark]] }, { label: "Control", items: [["Administración", "/administration", ShieldCheck], ["Configuración", "/settings", Settings2]] }];
export function AppShell({ children }: { children: React.ReactNode }) { const [open, setOpen] = useState(false); return <div className="min-h-screen p-3 md:p-4"><button onClick={() => setOpen(true)} className="glass fixed left-4 top-4 z-30 grid h-10 w-10 place-items-center rounded-lg md:hidden" aria-label="Abrir navegación"><Menu size={18}/></button><aside className={cn("glass fixed inset-y-3 left-3 z-40 flex w-64 flex-col rounded-2xl p-3 transition-transform md:translate-x-0", open ? "translate-x-0" : "-translate-x-[110%]")}><div className="flex h-12 items-center justify-between px-2"><div><span className="text-lg font-semibold tracking-tight">voyara</span><span className="ml-1 text-[10px] font-bold tracking-[.18em] text-accent">OPS</span></div><button onClick={() => setOpen(false)} className="md:hidden"><X size={18}/></button></div><div className="mt-5 flex-1 space-y-5 overflow-y-auto">{groups.map((group) => <div key={group.label}><p className="px-2 text-[10px] font-semibold uppercase tracking-[.14em] text-muted">{group.label}</p><nav className="mt-1 space-y-0.5">{group.items.map(([label, href, Icon]) => <Link onClick={() => setOpen(false)} href={href as string} key={label as string} className="flex items-center gap-3 rounded-lg px-2.5 py-2 text-sm text-muted transition hover:bg-ink/5 hover:text-ink"><Icon size={16}/>{label as string}</Link>)}</nav></div>)}</div><div className="rounded-lg bg-ink/5 p-3"><p className="text-xs font-medium">Caribbean DMC</p><p className="mt-0.5 text-[11px] text-muted">Punta Cana · USD</p></div></aside><main className="md:ml-[17rem]"><header className="glass sticky top-3 z-20 flex h-14 items-center justify-between rounded-xl px-3 sm:px-4"><div className="hidden items-center gap-2 text-sm text-muted md:flex"><span>Demo Travel Group</span><span className="text-line">/</span><span className="text-ink">Resumen operativo</span></div><button className="ml-12 flex items-center gap-2 rounded-lg border border-line/70 bg-surface/40 px-3 py-1.5 text-xs text-muted md:ml-0"><Command size={14}/>Buscar <span className="hidden rounded border border-line px-1 text-[10px] sm:inline">⌘ K</span></button><div className="flex items-center gap-1"><ThemeToggle/><button className="grid h-9 w-9 place-items-center rounded-lg text-muted hover:bg-ink/5" aria-label="Notificaciones"><Bell size={17}/></button><button className="flex items-center gap-2 rounded-lg px-2 py-1.5 text-left hover:bg-ink/5"><span className="grid h-6 w-6 place-items-center rounded-full bg-accent text-[10px] font-bold text-white">AM</span><ChevronDown size={14} className="text-muted"/></button></div></header><div className="mx-auto max-w-[1600px] px-1 py-7 sm:px-3">{children}</div></main></div>; }
