-- Testable travel-operating vertical slice. All financial fields use numeric, never floating point.
create table public.suppliers (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), code text not null, legal_name text not null, supplier_type text not null check (supplier_type in ('HOTEL','TRANSFER','ACTIVITY')), status text not null default 'ACTIVE', default_currency char(3) not null, country text not null, city text not null, created_at timestamptz not null default now(), unique (tenant_id, code));
create table public.products (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), supplier_id uuid not null references public.suppliers(id), code text not null, type text not null, name text not null, destination text not null, status text not null default 'ACTIVE', default_currency char(3) not null, created_at timestamptz not null default now(), unique (tenant_id, code));
create table public.contracts (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), supplier_id uuid not null references public.suppliers(id), code text not null, name text not null, valid_from date not null, valid_to date not null, currency char(3) not null, status text not null default 'ACTIVE', check (valid_to >= valid_from), unique (tenant_id, code));
create table public.contract_rates (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), contract_id uuid not null references public.contracts(id), product_id uuid not null references public.products(id), valid_from date not null, valid_to date not null, cost_amount numeric(20,6) not null check (cost_amount >= 0), currency char(3) not null, unit text not null, check (valid_to >= valid_from));
create table public.inventory (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), product_id uuid not null references public.products(id), service_date date not null, mode text not null check (mode in ('FREE_SALE','ON_REQUEST','ALLOTMENT')), available integer not null check (available >= 0), sold integer not null default 0 check (sold >= 0 and sold <= available), unique (product_id, service_date));
create table public.agencies (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), code text not null, name text not null, market text not null, country text not null, currency char(3) not null, credit_limit numeric(20,6) not null default 0, status text not null default 'ACTIVE', unique (tenant_id, code));
create table public.customers (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), first_name text not null, last_name text not null, email text, language text not null default 'en', created_at timestamptz not null default now());
create table public.quotes (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), reference text not null, agency_id uuid references public.agencies(id), customer_id uuid references public.customers(id), status text not null check (status in ('DRAFT','SENT','ACCEPTED','REJECTED','EXPIRED','CONVERTED')), travel_start date not null, travel_end date not null, currency char(3) not null, total_cost numeric(20,6) not null, total_sale numeric(20,6) not null, pricing_snapshot jsonb not null default '{}'::jsonb, unique (tenant_id, reference));
create table public.quote_services (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), quote_id uuid not null references public.quotes(id) on delete cascade, product_id uuid references public.products(id), service_date date not null, quantity integer not null check (quantity > 0), cost_amount numeric(20,6) not null, sale_amount numeric(20,6) not null, status text not null default 'OPTION');
create table public.bookings (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), reference text not null, quote_id uuid references public.quotes(id), agency_id uuid references public.agencies(id), customer_id uuid references public.customers(id), status text not null check (status in ('DRAFT','OPTION','REQUESTED','PARTIALLY_CONFIRMED','CONFIRMED','IN_PROGRESS','TRAVELLED','CANCELLED','CLOSED')), travel_start date not null, travel_end date not null, currency char(3) not null, total_cost numeric(20,6) not null, total_sale numeric(20,6) not null, pricing_snapshot jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique (tenant_id, reference));
create table public.booking_services (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), booking_id uuid not null references public.bookings(id) on delete cascade, product_id uuid references public.products(id), service_date date not null, status text not null check (status in ('DRAFT','REQUESTED','CONFIRMED','REJECTED','CANCELLED','COMPLETED')), cost_amount numeric(20,6) not null, sale_amount numeric(20,6) not null);
create table public.passengers (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), booking_id uuid not null references public.bookings(id) on delete cascade, first_name text not null, last_name text not null, passenger_type text not null check (passenger_type in ('ADT','CHD','INF','FOC','TOUR_LEADER')), nationality text, dob date);
create table public.operations_tasks (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), booking_id uuid references public.bookings(id), title text not null, due_at timestamptz not null, status text not null check (status in ('OPEN','IN_PROGRESS','DONE','CANCELLED')), priority text not null check (priority in ('LOW','NORMAL','HIGH')));
create table public.invoices (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), booking_id uuid references public.bookings(id), reference text not null, status text not null check (status in ('DRAFT','ISSUED','PAID','OVERDUE','VOID')), currency char(3) not null, total_amount numeric(20,6) not null, due_date date not null, unique (tenant_id, reference));
create table public.payments (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), invoice_id uuid references public.invoices(id), payment_date date not null, amount numeric(20,6) not null check (amount > 0), currency char(3) not null, method text not null);
create index products_tenant_supplier_idx on public.products(tenant_id, supplier_id); create index bookings_tenant_travel_idx on public.bookings(tenant_id, travel_start); create index quotes_tenant_status_idx on public.quotes(tenant_id, status);
do $$ declare t text; begin foreach t in array array['suppliers','products','contracts','contract_rates','inventory','agencies','customers','quotes','quote_services','bookings','booking_services','passengers','operations_tasks','invoices','payments'] loop execute format('alter table public.%I enable row level security', t); execute format('create policy "tenant read" on public.%I for select to authenticated using (tenant_id = (select tenant_id from public.profiles where id = auth.uid()))', t); end loop; end $$;
