import Link from "next/link";
import { ArrowUpRight, CalendarDays, CircleDollarSign, CreditCard, TrendingUp, UsersRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { GlassPanel, PageHeader } from "@/components/domain/ui";
import { getTenantContext } from "@/lib/tenant";

export default async function DashboardPage() {
  const { supabase, displayName } = await getTenantContext();
  const today = new Date(); const monthStart = new Date(today.getFullYear(), today.getMonth(), 1).toISOString(); const soon = new Date(today); soon.setDate(soon.getDate() + 14);
  const [{ data: bookings }, { data: quotes }, { data: invoices }, { data: tasks }, { data: activities }, { count: agencyCount }] = await Promise.all([
    supabase.from("bookings").select("id,reference,status,travel_start,total_sale,total_cost,currency").gte("created_at", monthStart),
    supabase.from("quotes").select("id,reference,status,total_sale,travel_start").order("created_at", { ascending: false }).limit(5),
    supabase.from("invoices").select("status,total_amount"),
    supabase.from("operations_tasks").select("id,title,status,priority,due_at").in("status", ["OPEN", "IN_PROGRESS"]).order("due_at").limit(5),
    supabase.from("activities").select("id,title,starts_at,status,activity_type").gte("starts_at", today.toISOString()).lte("starts_at", soon.toISOString()).order("starts_at").limit(8),
    supabase.from("agencies").select("id", { count: "exact", head: true }).eq("status", "ACTIVE")
  ]);
  const sales = bookings?.reduce((sum, item) => sum + Number(item.total_sale), 0) ?? 0;
  const profit = bookings?.reduce((sum, item) => sum + Number(item.total_sale) - Number(item.total_cost), 0) ?? 0;
  const receivables = invoices?.filter((item) => !["PAID", "VOID"].includes(item.status)).reduce((sum, item) => sum + Number(item.total_amount), 0) ?? 0;
  const metrics = [["Ventas del mes", `USD ${sales.toLocaleString("es-ES", { maximumFractionDigits: 0 })}`, CircleDollarSign], ["Reservas", String(bookings?.length ?? 0), CalendarDays], ["Beneficio previsto", `USD ${profit.toLocaleString("es-ES", { maximumFractionDigits: 0 })}`, TrendingUp], ["Cuentas por cobrar", `USD ${receivables.toLocaleString("es-ES", { maximumFractionDigits: 0 })}`, CreditCard]] as const;
  return <AppShell>
    <PageHeader eyebrow="Centro de control" title={`Buenos días, ${displayName}.`} description="Ventas, agenda y prioridades calculadas con datos operativos reales." actions={<Link href="/sales" className="rounded-lg bg-accent px-4 py-2.5 text-sm font-semibold text-white">Crear cotización</Link>}/>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([metricLabel, value, Icon]) => <GlassPanel key={metricLabel} className="p-4"><div className="flex items-start justify-between"><p className="text-xs font-medium text-muted">{metricLabel}</p><Icon size={16} className="text-accent"/></div><p className="mt-5 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted">Actualizado ahora</p></GlassPanel>)}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_1fr]">
      <GlassPanel className="overflow-hidden"><div className="flex items-center justify-between p-5"><div><h2 className="font-semibold">Actividad comercial reciente</h2><p className="mt-1 text-xs text-muted">Cotizaciones listas para seguimiento o conversión.</p></div><Link href="/sales" className="text-xs font-semibold text-accent">Gestionar ventas <ArrowUpRight className="inline" size={13}/></Link></div><div className="divide-y">{quotes?.map((quote) => <div key={quote.id} className="flex items-center justify-between p-4"><div><p className="font-mono text-sm font-semibold text-accent">{quote.reference}</p><p className="mt-1 text-xs text-muted">Servicio {quote.travel_start} · {quote.status}</p></div><div className="text-right"><p className="font-semibold">USD {Number(quote.total_sale).toFixed(2)}</p><Link href={`/documents/quote/${quote.id}`} className="text-xs text-accent">Abrir cotización</Link></div></div>)}</div></GlassPanel>
      <GlassPanel className="overflow-hidden"><div className="flex items-center justify-between p-5"><div><h2 className="font-semibold">Cola de atención</h2><p className="mt-1 text-xs text-muted">Revisa, asigna o completa tareas.</p></div><span className="rounded-md bg-amber-500/10 px-2 py-1 text-xs font-semibold text-amber-700">{tasks?.length ?? 0} abiertas</span></div><div className="divide-y">{tasks?.map((task) => <div key={task.id} className="flex items-center justify-between gap-3 p-4"><div><p className="text-sm font-medium">{task.title}</p><p className="mt-1 text-xs text-muted">{new Date(task.due_at).toLocaleDateString("es-ES")} · {task.priority === "HIGH" ? "Prioridad alta" : "Prioridad normal"}</p></div><Link href="/operations" className="text-xs font-semibold text-accent">{task.status === "OPEN" ? "Revisar" : "Abrir"}</Link></div>)}</div>{!tasks?.length ? <p className="p-5 text-sm text-muted">No hay tareas pendientes.</p> : null}</GlassPanel>
    </section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_1fr]">
      <GlassPanel className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Próximas actividades</h2><p className="mt-1 text-xs text-muted">Calendario de servicios para los próximos 14 días.</p></div><Link href="/operations" className="text-xs font-semibold text-accent">Abrir calendario →</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{activities?.map((activity) => <div key={activity.id} className="rounded-xl border bg-surface/50 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-accent">{new Date(activity.starts_at).toLocaleDateString("es-ES", { weekday: "short", day: "2-digit", month: "short" })}</p><p className="mt-2 text-sm font-medium">{activity.title}</p><p className="mt-1 text-xs text-muted">{activity.activity_type} · {activity.status}</p></div>)}</div>{!activities?.length ? <p className="mt-5 text-sm text-muted">Convierte una cotización en reserva para generar actividades.</p> : null}</GlassPanel>
      <GlassPanel className="p-5"><div className="flex items-center gap-2"><UsersRound size={16} className="text-accent"/><h2 className="font-semibold">Canal comercial</h2></div><div className="mt-6 space-y-4"><div className="flex justify-between border-b pb-3"><span className="text-sm text-muted">Agencias activas</span><span className="font-semibold">{agencyCount ?? 0}</span></div><div className="flex justify-between border-b pb-3"><span className="text-sm text-muted">Cotizaciones abiertas</span><span className="font-semibold">{quotes?.filter((quote) => quote.status !== "CONVERTED").length ?? 0}</span></div><Link href="/crm?view=agencies" className="block rounded-lg border px-3 py-2.5 text-center text-sm font-semibold text-accent">Gestionar agencias</Link><Link href="/products" className="block rounded-lg border px-3 py-2.5 text-center text-sm font-semibold text-accent">Gestionar tarifas</Link></div></GlassPanel>
    </section>
  </AppShell>;
}
