import Link from "next/link";
import { notFound } from "next/navigation";
import { PrintButton } from "@/components/domain/print-button";
import { getTenantContext } from "@/lib/tenant";

export default async function DocumentPage({ params }: { params: Promise<{ type: string; id: string }> }) {
  const { type, id } = await params; const { supabase } = await getTenantContext();
  if (type === "quote") {
    const { data: quote } = await supabase.from("quotes").select("*,agencies(*),customers(*),quote_services(*,products(name,code,destination))").eq("id", id).single();
    if (!quote) notFound(); const agency = Array.isArray(quote.agencies) ? quote.agencies[0] : quote.agencies; const customer = Array.isArray(quote.customers) ? quote.customers[0] : quote.customers;
    return <DocumentFrame title="Cotización" reference={quote.reference}><Party name={agency?.name ?? `${customer?.first_name ?? ""} ${customer?.last_name ?? ""}`.trim()} detail={agency ? `${agency.code} · ${agency.country} · ${agency.email ?? ""}` : `${customer?.email ?? ""} · ${customer?.phone ?? ""}`}/><table className="mt-8 w-full text-left text-sm"><thead className="border-y"><tr><th className="py-3">Servicio</th><th>Fecha</th><th>Cant.</th><th className="text-right">Importe</th></tr></thead><tbody>{quote.quote_services?.map((service: Record<string, any>) => { const product = Array.isArray(service.products) ? service.products[0] : service.products; return <tr key={service.id} className="border-b"><td className="py-4"><p className="font-medium">{product?.name}</p><p className="text-xs text-slate-500">{product?.code} · {product?.destination}</p></td><td>{service.service_date}</td><td>{service.quantity}</td><td className="text-right">{quote.currency} {Number(service.sale_amount).toFixed(2)}</td></tr>; })}</tbody></table><Total currency={quote.currency} amount={quote.total_sale}/><p className="mt-8 text-sm text-slate-600">{quote.notes || "Precios sujetos a disponibilidad hasta la conversión de la cotización en reserva."}</p></DocumentFrame>;
  }
  if (type === "invoice") {
    const { data: invoice } = await supabase.from("invoices").select("*,bookings(*,agencies(*),customers(*),booking_services(*,products(name,code,destination)))").eq("id", id).single();
    if (!invoice) notFound(); const booking = Array.isArray(invoice.bookings) ? invoice.bookings[0] : invoice.bookings; const agency = Array.isArray(booking?.agencies) ? booking.agencies[0] : booking?.agencies; const customer = Array.isArray(booking?.customers) ? booking.customers[0] : booking?.customers;
    return <DocumentFrame title="Factura / comprobante" reference={invoice.reference}><Party name={agency?.name ?? `${customer?.first_name ?? ""} ${customer?.last_name ?? ""}`.trim()} detail={`Reserva ${booking?.reference} · Vencimiento ${invoice.due_date}`}/><table className="mt-8 w-full text-left text-sm"><thead className="border-y"><tr><th className="py-3">Servicio</th><th>Fecha</th><th className="text-right">Importe</th></tr></thead><tbody>{booking?.booking_services?.map((service: Record<string, any>) => { const product = Array.isArray(service.products) ? service.products[0] : service.products; return <tr key={service.id} className="border-b"><td className="py-4"><p className="font-medium">{product?.name}</p><p className="text-xs text-slate-500">{product?.code} · {product?.destination}</p></td><td>{service.service_date}</td><td className="text-right">{invoice.currency} {Number(service.sale_amount).toFixed(2)}</td></tr>; })}</tbody></table><Total currency={invoice.currency} amount={invoice.total_amount}/></DocumentFrame>;
  }
  notFound();
}

function DocumentFrame({ title, reference, children }: { title: string; reference: string; children: React.ReactNode }) { return <main className="min-h-screen bg-white p-5 text-slate-900 sm:p-10"><div className="mx-auto max-w-4xl"><div className="mb-6 flex items-center justify-between print:hidden"><Link href="/dashboard" className="text-sm font-semibold text-teal-700">← Volver al sistema</Link><PrintButton/></div><article className="rounded-2xl border p-7 shadow-sm print:border-0 print:p-0 print:shadow-none"><header className="flex items-start justify-between border-b pb-7"><div><p className="text-2xl font-bold tracking-tight">voyara</p><p className="mt-1 text-xs uppercase tracking-[.2em] text-teal-700">Demo Travel Group</p></div><div className="text-right"><h1 className="text-2xl font-semibold">{title}</h1><p className="mt-1 font-mono text-sm text-slate-500">{reference}</p><p className="mt-1 text-xs text-slate-500">Emitido: {new Intl.DateTimeFormat("es-ES", { dateStyle: "long" }).format(new Date())}</p></div></header>{children}<footer className="mt-12 border-t pt-5 text-xs text-slate-500">Documento generado por Voyara Travel ERP · Demo Travel Group · Punta Cana, República Dominicana</footer></article></div></main>; }
function Party({ name, detail }: { name: string; detail: string }) { return <section className="mt-7"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Facturar / presentar a</p><p className="mt-2 text-lg font-semibold">{name || "Titular no especificado"}</p><p className="mt-1 text-sm text-slate-500">{detail}</p></section>; }
function Total({ currency, amount }: { currency: string; amount: number }) { return <div className="mt-6 flex justify-end"><div className="w-72 rounded-xl bg-slate-50 p-4"><div className="flex justify-between text-lg font-semibold"><span>Total</span><span>{currency} {Number(amount).toFixed(2)}</span></div><p className="mt-1 text-right text-xs text-slate-500">Impuestos y condiciones según contrato.</p></div></div>; }
